# Mount a live checkout as admin-release.
version: "3.7"

services:
  admin-nginx:
    environment:
      VIRTUAL_HOST: admin.${DOCKER_BASE_DOMAIN}
      APP_ENV: "dev"
      APP_DEBUG: "1"

  admin-php:
    environment:
      XDEBUG_CONFIG: "idekey=VSCODE"
      PHP_IDE_CONFIG: "serverName=admin.${DOCKER_BASE_DOMAIN}"
      APP_ENV: "dev"
      APP_DEBUG: "1"

  admin-cron:
    environment:
      APP_ENV: "dev"
      APP_DEBUG: "1"

  nginx-proxy:
    image: jwilder/nginx-proxy
    depends_on:
      - admin-nginx
      - admin-php
      - screen
      - search
      - middleware
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - "./nginx_proxy_upload_maxsize.conf:/etc/nginx/conf.d/nginx_proxy_upload_maxsize.conf"

volumes:
  admin-release:
    driver_opts:
      type: none
      device: $PWD/development
      o: bind
      
  admin-uploads:
    driver_opts:
      type: none
      device: $PWD/development/admin/web/uploads
      o: bind
