# Mount a live checkout as admin-release.
version: "3.7"

services:
  admin-nginx:
    environment:
      VIRTUAL_HOST: admin.${DOCKER_BASE_DOMAIN}
      SYMFONY_ENV: "prod"
      SYMFONY_DEBUG: "0"

  admin-php:
    environment:
      PHP_IDE_CONFIG: "serverName=admin.${DOCKER_BASE_DOMAIN}"
      SYMFONY_ENV: "prod"
      SYMFONY_DEBUG: "0"

  admin-cron:
    environment:
      PHP_IDE_CONFIG: "serverName=cron.${DOCKER_BASE_DOMAIN}"
      SYMFONY_ENV: "prod"
      SYMFONY_DEBUG: "0"

  nginx-proxy:
    image: jwilder/nginx-proxy
    depends_on:
      - admin-nginx
      - admin-php
      - screen
      - search
      - middleware
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /etc/ssl/nginx:/etc/nginx/certs

volumes:
  admin-release:
    driver_opts:
      type: none
      device: $PWD/development
      o: bind
