# Mount a live checkout as admin-release.
version: "3.7"

services:
  admin-nginx:
    environment:
      VIRTUAL_HOST: admin.${DOCKER_BASE_DOMAIN}
      APP_ENV: "dev"
      APP_DEBUG: "0"

  admin-php:
    environment:
      PHP_IDE_CONFIG: "serverName=admin.${DOCKER_BASE_DOMAIN}"
      APP_ENV: "dev"
      APP_DEBUG: "0"

  admin-cron:
    environment:
      APP_ENV: "dev"
      APP_DEBUG: "0"

  nginx-proxy:
    image: jwilder/nginx-proxy
    depends_on:
      - admin-nginx
      - admin-php
      - screen
      - search
      - middleware
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /etc/ssl/nginx:/etc/nginx/certs

  db-backup:
    image: databack/mysql-backup
    volumes:
      - /home/dkagms/db-backup:/db
    environment:
      - DB_DUMP_TARGET=/db
      - DB_USER=os2display
      - DB_PASS=os2display
      - DB_SERVER=admin-db
      - DB_DUMP_BEGIN=+5


volumes:
  admin-release:
    driver_opts:
      type: none
      device: $PWD/development
      o: bind